node {
  def commit_id

  try {
      stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
      }
      stage('test') {
        sh './mvnw install && ./mvnw test && ./mvnw package'        
      }
      stage('docker build/push') {            
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
          def app = docker.build("marceloweb/spring-boot-demo:${commit_id}", '.')
          app.push()
          app.push('latest')
        }                                     
      }
    } catch(e) {

       slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

    throw e;
   }                                     
}                                          
