apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
spec:
  containers:
    - name: spring-boot-example
      image: marceloweb/spring-boot-demo:91e42b0
      ports:
         - containerPort: 8080
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
