version: "3"
services:
   jenkins:
      image: marceloweb/jenkins-docker:1.2
      privileged: true
      ports:
         - "8081:8080"
         - "50000:50000"
      volumes:
         - jenkins-data:/var/jenkins_home/
         - /var/run/docker.sock:/var/run/docker.sock
         - /opt/credentials:/opt/credentials
      links:
         - db
      environment:
         DB_HOST: db
         DB_NAME: example
         DB_USER: <db-user>
         DB_PASSWD: <db-password>
         GOOGLE_APPLICATION_CREDENTIALS: /opt/credentials/my-credential-gcp.json
         GCP_PROJECT: <gcp-project>
         GCP_REGION: <gcp-region>
         GCP_ACCOUNT: <gcp-account>
         CREDENTIALS: /opt/credentials/credentials.txt
   db:
      image: mariadb
      privileged: true
      restart: always
      ports:
         - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root        
volumes:
   jenkins-data:
      driver: local
